### ISSUE TITLE
will the plugin support maven, i am use maven to create an android project!

### ISSUE THREAD

**Issue by wsdjeg** [DonnieWest/VimStudio#5]
for now on
i use maven package android:deploy install the app to my phone
and use adb logcat read the log
also javacomplete2 can read my pom.xml 
so i can use YCM and javacomplete2 finish my android code compleion!
but i find javacomplete2 can not complete some method of Activity,such as `onStop()`

**Comment by DonnieWest** [comment]
I'm afraid Maven will not be supported by VimStudio. Gradle is the official Android build system and you'll find that you're going to experience a ton of pain to use Maven as your Android build system

**Comment by wsdjeg** [comment]
di you use javacomplete2 ,can the plugin complete all the method of a class .i find it can not complete onCreate also can not import class which is definded in a class

**Comment by DonnieWest** [comment]
This plugin is created to be used with JavaComplete2 and I believe supports everything you're mentioning. If you notice any issues, feel free to submit an issue :)

That being said...

![2015-10-19-211815_640x360_scrot-thumb](https://cloud.githubusercontent.com/assets/1453484/10596193/26b4cdde-76a7-11e5-89c7-3d5d34e74f1c.png)

**Comment by DonnieWest** [comment]
@wsdeg what you might be missing from JavaComplete2 is your android.jar file. Try adding that to g:JavaComplete_LibsPath and see if you get onCreate completions like you want.

**Comment by wsdjeg** [comment]
thank you i have fix it by change dependency 
![2015-10-20 20-07-20](https://cloud.githubusercontent.com/assets/13142418/10612406/39a333ea-7783-11e5-826d-81ac84780b84.png)

and mvn alse can jenerate R.java

``` shell
mvn android:generate-sources
```
