### ISSUE TITLE
javacomplete2 can not import R.java and can not complete filed of inner class

### ISSUE THREAD

**Issue by wsdjeg** [DonnieWest/VimStudio#6]
hi donniewest
here is a problem i got
https://github.com/artur-shaik/vim-javacomplete2/issues/116 

can you fix it

**Comment by DonnieWest** [comment]
@wsdjeg that's not a problem with VimStudio.  I'll take a look at it though on JavaComplete2

**Comment by wsdjeg** [comment]
thank you very much
