### ISSUE TITLE
how to use .why SetupVimStudio is not a command

### ISSUE THREAD

**Issue by wsdjeg** [DonnieWest/VimStudio#9]
here is my init.vim
![2015-11-17 20-41-20](https://cloud.githubusercontent.com/assets/13142418/11211847/5038e82a-8d6d-11e5-84eb-4cecc401f49d.png)

i have delete `"` before Plugin 'DonnieWest/VimStudio'

echo has("python3") return 1

**Comment by DonnieWest** [comment]
There's a few possibilities, but I think my plugin isn't currently compatible with the latest JavaComplete2

I'm going to do some major changes soon to fix that and I'll revisit this then.

**Comment by wsdjeg** [comment]
1. any possiable provide vim support?
2.  i think people also use many plugins ,for jave  i am using syntastic javacomplete2 and so on ,i think these plugins should not do repeat things,for example load classpath of current project,now javacomplete can do these ,maybe it's better to let javacomplete2 provide a g:Javacomplete_current_project_classpath ,this variable should be locked ,can be used by other plugin,but should not be used by javacomplete2

**Comment by DonnieWest** [comment]
1. If you need Vim support, feel free to use [Vim Grand](https://github.com/DonnieWest/vim-grand). That right there is a fork for all Gradle projects
2. I plan to modify the existing syntastic support to use JavaComplete2's classpath and source path. I think I can do that without a change to JavaComplete :)

**Comment by wsdjeg** [comment]
I  have read syntastic src,and i think syntastic just need two things,classpath and outputdirectory,then if set do not delete outputfile,auto compile will be achieved

**Comment by DonnieWest** [comment]
@wsdjeg this should work now. Let me know how you like it

**Comment by wsdjeg** [comment]
i will check it tonight

**Comment by wsdjeg** [comment]
still can not find this command
here is my vimrc
![2015-11-18 19-32-45](https://cloud.githubusercontent.com/assets/13142418/11240129/28ceb030-8e2b-11e5-9c6a-da40eda08222.png)

**Comment by wsdjeg** [comment]
type  :S then type tab only Sexplore

**Comment by DonnieWest** [comment]
After installing, did you run :UpdateRemotePlugins and restart neovim?

**Comment by wsdjeg** [comment]
i have restarted nvim but still can not find this command ,my os is ubuntu15.10

**Comment by DonnieWest** [comment]
Latest should check for the command and forces an update - how's it working for you?

**Comment by DonnieWest** [comment]
Hah. I sent up that update, refreshed my Neovim and experienced the same issues you have been. Bizarre. Figuring it out.

**Comment by DonnieWest** [comment]
Latest update works on my machine

**Comment by wsdjeg** [comment]
thank you  i will check tonight!

**Comment by wsdjeg** [comment]
still can not find this command

**Comment by wsdjeg** [comment]
can you please try with the same init.vim as me ,and put the plugin in ~/.config/nvim/bundle

**Comment by DonnieWest** [comment]
I'm afraid I'm using VimPlug - you might try installing with that and the latest Neovim

I've tried this process on a couple computers now, can't replicate the :SetupVimStudio command not showing

**Comment by wsdjeg** [comment]
both of these plugin manager just set rtp+=path to plugin,is it right?

**Comment by DonnieWest** [comment]
I'm not sure honestly. The less variables between my setup and yours the better. My init.vim is public so you're welcome to try my exact setup.

**Comment by wsdjeg** [comment]
i will test it tonight,thank you

**Comment by wsdjeg** [comment]
still not working, maybe it is due to my neovim ,
